name: Daily ESPN Scraper

on:
  schedule:
    # Runs at 10:00 UTC every day (Adjust to be after games finish)
    - cron: '0 10 * * *'
  workflow_dispatch: # Allows you to click "Run Now" manually

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pandas supabase google-cloud-storage

      - name: Run Scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCP_SA_KEY }}
        run: python daily_scraper.py
