-- SQL schema for flattened player_owner_season_stats table in Supabase
CREATE TABLE IF NOT EXISTS public.player_owner_season_stats (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    league_id BIGINT NOT NULL,
    season_year INT NOT NULL,
    team_id INT NOT NULL,
    owner_name TEXT,
    player_id INT NOT NULL,
    player_name TEXT,
    positions TEXT,
    is_pitcher BOOLEAN DEFAULT FALSE,
    is_batter BOOLEAN DEFAULT FALSE,
    days_active INT DEFAULT 0,
    days_bench INT DEFAULT 0,
    days_il INT DEFAULT 0,
    days_total INT DEFAULT 0,
    -- Batting
    pa INT DEFAULT 0,
    ab INT DEFAULT 0,
    h INT DEFAULT 0,
    r INT DEFAULT 0,
    hr INT DEFAULT 0,
    rbi INT DEFAULT 0,
    sb INT DEFAULT 0,
    bb INT DEFAULT 0,
    so INT DEFAULT 0,
    d2 INT DEFAULT 0,
    d3 INT DEFAULT 0,
    tb INT DEFAULT 0,
    sf INT DEFAULT 0,
    hbp INT DEFAULT 0,
    cs INT DEFAULT 0,
    avg FLOAT8 DEFAULT 0,
    obp FLOAT8 DEFAULT 0,
    slg FLOAT8 DEFAULT 0,
    ops FLOAT8 DEFAULT 0,
    -- Pitching
    gs INT DEFAULT 0,
    ip_outs INT DEFAULT 0,
    ip FLOAT8 DEFAULT 0,
    k INT DEFAULT 0,
    qs INT DEFAULT 0,
    w INT DEFAULT 0,
    l INT DEFAULT 0,
    sv INT DEFAULT 0,
    hd INT DEFAULT 0,
    sv_hd INT DEFAULT 0,
    er INT DEFAULT 0,
    h_allowed INT DEFAULT 0,
    bb_allowed INT DEFAULT 0,
    r_allowed INT DEFAULT 0,
    era FLOAT8 DEFAULT 0,
    whip FLOAT8 DEFAULT 0,
    k_9 FLOAT8 DEFAULT 0,
    bb_9 FLOAT8 DEFAULT 0,
    qs_pct FLOAT8 DEFAULT 0,
    -- Bench stats
    bench_pa INT DEFAULT 0,
    bench_h INT DEFAULT 0,
    bench_r INT DEFAULT 0,
    bench_hr INT DEFAULT 0,
    bench_rbi INT DEFAULT 0,
    bench_sb INT DEFAULT 0,
    bench_ip_outs INT DEFAULT 0,
    bench_k INT DEFAULT 0,
    bench_qs INT DEFAULT 0,
    bench_sv_hd INT DEFAULT 0,
    bench_er INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (league_id, season_year, team_id, player_id)
);

CREATE INDEX IF NOT EXISTS idx_poss_season_owner ON public.player_owner_season_stats(season_year, owner_name);
CREATE INDEX IF NOT EXISTS idx_poss_player ON public.player_owner_season_stats(player_id);
